kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: blue-green-route
  annotations:
    haproxy.router.openshift.io/balance: random
spec:
  to:
    kind: Service
    name: user10-hello-chart
    weight: 10
  alternateBackends:
  - kind: Service
    name: hai30-hello-world
    weight: 20