ReplicaNumber: 3

containers:
  containerPort: 8080
  image: 'quay.io/hai30/helloworld'
  tag: 'chart_v1'

probes:
  readiness:
    path: /health/readiness
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
  liveness:
    path: health/liveliness
    initialDelaySeconds: 1
    timeoutSeconds: 1
    periodSeconds: 10
    successThreshold: 1
    failureThreshold: 3
volume:
  mount:
    path: /tmp/html

test: Healty

service:
  servicePort: 8080